/**
 * Pure computation of rule proof coverage and its Markdown report.
 */
import type { RuleProof } from './jest-report.ts';
import { describeCodeLevelRanges, expectedCodeLevelIds, isCodeLevel } from './rule-ids.ts';

/** Tests proving one rule. */
export interface RuleEntry {
  /** Rule identifier. */
  readonly rule: string;
  /** Full names of the passing tests that prove it. */
  readonly tests: readonly string[];
}

/** Result of checking code-level rules against test proofs. */
export interface CoverageResult {
  /** Code-level rules of the specification, in order. */
  readonly rules: readonly string[];
  /** Tests proving each rule, in rule order. */
  readonly entries: readonly RuleEntry[];
  /** Number of rules with at least one passing test. */
  readonly proven: number;
  /** Rules without proof that are not in the allow-missing list (failures). */
  readonly missing: readonly string[];
  /** Rules without proof tolerated by the allow-missing list. */
  readonly pending: readonly string[];
  /** Code-level identifiers expected by the ranges but absent from the specification. */
  readonly absentFromSpec: readonly string[];
}

/** Report status of one rule. */
type RuleStatus = 'proven' | 'pending' | 'missing';

/**
 * Parses an allow-missing list: one rule per line, `#` starts a comment, blanks ignored.
 * @param text - List content.
 * @returns The rule identifiers listed.
 */
export function parseAllowList(text: string): Set<string> {
  const ids = new Set<string>();
  for (const line of text.split('\n')) {
    const hash = line.indexOf('#');
    const id = (hash >= 0 ? line.slice(0, hash) : line).trim();
    if (id !== '') {
      ids.add(id);
    }
  }
  return ids;
}

/**
 * Checks which code-level rules have at least one passing test.
 * @param specRules - Rule identifiers declared in the specification.
 * @param proofs - Proofs collected from the Jest reports.
 * @param allowMissing - Rules tolerated without proof (temporary list).
 * @returns The coverage result.
 */
export function checkCoverage(
  specRules: readonly string[],
  proofs: readonly RuleProof[],
  allowMissing: ReadonlySet<string>,
): CoverageResult {
  const rules = specRules.filter(isCodeLevel);
  const testsByRule = new Map<string, string[]>();
  for (const proof of proofs) {
    testsByRule.set(proof.rule, [...(testsByRule.get(proof.rule) ?? []), proof.test]);
  }
  const entries = rules.map((rule) => ({ rule, tests: testsByRule.get(rule) ?? [] }));
  const unproven = entries.filter((e) => e.tests.length === 0).map((e) => e.rule);
  const declared = new Set(specRules);
  return {
    rules,
    entries,
    proven: rules.length - unproven.length,
    missing: unproven.filter((r) => !allowMissing.has(r)),
    pending: unproven.filter((r) => allowMissing.has(r)),
    absentFromSpec: expectedCodeLevelIds().filter((id) => !declared.has(id)),
  };
}

/**
 * Escapes text for a Markdown table cell.
 * @param text - Raw cell text.
 * @returns Text safe inside a table cell.
 */
function escapeCell(text: string): string {
  return text.split('|').join('\\|').split('\n').join(' ');
}

/**
 * Classifies one rule entry for the report.
 * @param entry - Rule and its proofs.
 * @param pending - Rules tolerated by the allow list.
 * @returns The report status.
 */
function statusOf(entry: RuleEntry, pending: ReadonlySet<string>): RuleStatus {
  if (entry.tests.length > 0) {
    return 'proven';
  }
  return pending.has(entry.rule) ? 'pending' : 'missing';
}

/**
 * Renders the coverage result as the evidence Markdown (`docs/evidence/rules-coverage.md`).
 * @param result - Coverage result.
 * @param specPath - Specification the rules were read from.
 * @returns Markdown document.
 */
export function renderReport(result: CoverageResult, specPath: string): string {
  const pending = new Set(result.pending);
  const lines = [
    '# Rules coverage',
    '',
    `> Generated by \`npm run rules:coverage\`. Code-level rules of \`${specPath}\``,
    `> (${describeCodeLevelRanges()}) mapped to the passing tests that prove them.`,
    '',
    `Proven: **${result.proven}/${result.rules.length}** · pending (allow-list): ${result.pending.length} · missing: ${result.missing.length}`,
    '',
    '| Rule | Status | Tests |',
    '|---|---|---|',
  ];
  for (const entry of result.entries) {
    lines.push(`| ${entry.rule} | ${statusOf(entry, pending)} | ${entry.tests.map(escapeCell).join('<br>')} |`);
  }
  return `${lines.join('\n')}\n`;
}
