/**
 * Pure computation of rule proof coverage and its Markdown report.
 */
import { isCodeLevel } from './rule-ids.ts';
import type { RuleProof } from './jest-report.ts';

/** Tests proving one rule. */
export interface RuleEntry {
  /** Rule identifier. */
  readonly rule: string;
  /** Full names of the passing tests that prove it. */
  readonly tests: readonly string[];
}

/** Result of checking code-level rules against test proofs. */
export interface CoverageResult {
  /** Code-level rules of the specification, in order. */
  readonly rules: readonly string[];
  /** Tests proving each rule, in rule order. */
  readonly entries: readonly RuleEntry[];
  /** Rules without proof that are not in the allow-missing list (failures). */
  readonly missing: readonly string[];
  /** Rules without proof tolerated by the allow-missing list. */
  readonly pending: readonly string[];
}

/**
 * Parses an allow-missing list: one rule per line, `#` starts a comment, blanks ignored.
 * @param text - List content.
 * @returns The rule identifiers listed.
 */
export function parseAllowList(text: string): Set<string> {
  const ids = new Set<string>();
  for (const line of text.split('\n')) {
    const hash = line.indexOf('#');
    const id = (hash >= 0 ? line.slice(0, hash) : line).trim();
    if (id !== '') {
      ids.add(id);
    }
  }
  return ids;
}

/**
 * Checks which code-level rules have at least one passing test.
 * @param specRules - Rule identifiers declared in the specification.
 * @param proofs - Proofs collected from the Jest reports.
 * @param allowMissing - Rules tolerated without proof (temporary list).
 * @returns The coverage result.
 */
export function checkCoverage(
  specRules: readonly string[],
  proofs: readonly RuleProof[],
  allowMissing: ReadonlySet<string>,
): CoverageResult {
  const rules = specRules.filter(isCodeLevel);
  const entries = rules.map((rule) => ({ rule, tests: proofs.filter((p) => p.rule === rule).map((p) => p.test) }));
  const unproven = entries.filter((e) => e.tests.length === 0).map((e) => e.rule);
  return {
    rules,
    entries,
    missing: unproven.filter((r) => !allowMissing.has(r)),
    pending: unproven.filter((r) => allowMissing.has(r)),
  };
}

/**
 * Escapes a table cell for Markdown.
 * @param text - Raw cell text.
 * @returns Text safe inside a table cell.
 */
function cell(text: string): string {
  return text.split('|').join('\\|').split('\n').join(' ');
}

/**
 * Renders the coverage result as the evidence Markdown (`docs/evidence/rules-coverage.md`).
 * @param result - Coverage result.
 * @returns Markdown document.
 */
export function renderReport(result: CoverageResult): string {
  const proven = result.rules.length - result.missing.length - result.pending.length;
  const lines = [
    '# Rules coverage',
    '',
    '> Generated by `npm run rules:coverage`. Code-level rules of `docs/specs/warlog/spec.md`',
    '> (WL-01..WL-49, WL-57..WL-75, SEC-21..SEC-24) mapped to the passing tests that prove them.',
    '',
    `Proven: **${proven}/${result.rules.length}** · pending (allow-list): ${result.pending.length} · missing: ${result.missing.length}`,
    '',
    '| Rule | Status | Tests |',
    '|---|---|---|',
  ];
  for (const { rule, tests } of result.entries) {
    const status = tests.length > 0 ? 'proven' : result.pending.includes(rule) ? 'pending' : 'missing';
    lines.push(`| ${rule} | ${status} | ${tests.map(cell).join('<br>')} |`);
  }
  return `${lines.join('\n')}\n`;
}
