/**
 * Entity persistence (WL-04, WL-08, WL-41, WL-42, WL-46): one Markdown file per entity,
 * atomic writes, optimistic concurrency by `rev` under a short exclusive lock. Timestamps are
 * recorded for sorting and history only, never for conflict detection.
 */
import { WarlogError } from '../errors/warlog-error.ts';
import type { Clock } from '../ports/clock.port.ts';
import type { FileSystem } from '../ports/file-system.port.ts';
import type { MachineIdProvider } from '../ports/machine-id.port.ts';
import type { EntityPaths } from './entity-paths.ts';
import type { EntityRecord, EntityRef } from './entity-ref.ts';
import { MANAGED_FIELDS } from './entity-ref.ts';
import { parseFrontMatter, stringifyFrontMatter } from './front-matter-codec.ts';

/** Collaborators of {@link EntityFileRepository}. */
export interface EntityRepositoryDeps {
  /** File system. */
  readonly fs: FileSystem;
  /** Entity paths. */
  readonly paths: EntityPaths;
  /** Clock. */
  readonly clock: Clock;
  /** Machine id of the writer. */
  readonly machine: MachineIdProvider;
}

/** Changes applied by {@link EntityFileRepository.update}. */
export interface EntityChange {
  /** Fields to set (`undefined` removes a field); managed fields are ignored. */
  readonly patch: Readonly<Record<string, unknown>>;
  /** New body (unchanged when omitted). */
  readonly body?: string;
}

/**
 * Removes managed fields from caller input.
 * @param fields - Caller fields.
 * @returns Fields without `id`, `type`, `rev`, dates and `machine`.
 */
function unmanaged(fields: Readonly<Record<string, unknown>>): Record<string, unknown> {
  return Object.fromEntries(Object.entries(fields).filter(([k]) => !MANAGED_FIELDS.includes(k)));
}

/** Reads and writes entity files. */
export class EntityFileRepository {
  /** Collaborators. */
  private readonly deps: EntityRepositoryDeps;

  /**
   * Creates the repository.
   * @param deps - Collaborators.
   */
  constructor(deps: EntityRepositoryDeps) {
    this.deps = deps;
  }

  /**
   * Reads an entity.
   * @param ref - Entity reference.
   * @returns The record.
   * @throws {WarlogError} `NOT_FOUND`; `INVALID_FILE` when malformed or when its id/type do not match.
   */
  async read(ref: EntityRef): Promise<EntityRecord> {
    const path = await this.deps.paths.pathFor(ref);
    const doc = parseFrontMatter(await this.deps.fs.readFile(path), path);
    if (doc.data['id'] !== ref.id || doc.data['type'] !== ref.type || typeof doc.data['rev'] !== 'number') {
      throw new WarlogError('INVALID_FILE', `${path}: id, type or rev do not match the file location`, { reason: 'front_matter', file: path });
    }
    return doc;
  }

  /**
   * Creates an entity with `rev: 1`.
   * @param ref - Entity reference (id generated by the caller).
   * @param fields - Entity fields.
   * @param body - Markdown body.
   * @returns The stored record.
   * @throws {WarlogError} `CONFLICT` when the entity already exists.
   */
  async create(ref: EntityRef, fields: Readonly<Record<string, unknown>>, body = ''): Promise<EntityRecord> {
    const path = await this.deps.paths.pathFor(ref);
    return this.locked(path, async () => {
      if ((await this.deps.fs.stat(path)) !== undefined) {
        throw new WarlogError('CONFLICT', `${ref.type} ${ref.id} already exists`, { id: ref.id });
      }
      const now = this.deps.clock.now().toISOString();
      const data = { ...unmanaged(fields), id: ref.id, type: ref.type, rev: 1, created_at: now, updated_at: now, machine: await this.deps.machine.get() };
      return this.write(path, { data, body });
    });
  }

  /**
   * Updates an entity when the caller's `rev` is current (WL-42).
   * @param ref - Entity reference.
   * @param change - Patch and optional body.
   * @param expectedRev - Revision the change was based on.
   * @returns The stored record (`rev` incremented).
   * @throws {WarlogError} `CONFLICT` with the current state when `expectedRev` is stale; `NOT_FOUND`.
   */
  async update(ref: EntityRef, change: EntityChange, expectedRev: number): Promise<EntityRecord> {
    const path = await this.deps.paths.pathFor(ref);
    return this.locked(path, async () => {
      const current = await this.read(ref);
      const rev = Number(current.data['rev']);
      if (rev !== expectedRev) {
        throw new WarlogError('CONFLICT', `${ref.type} ${ref.id} changed since rev ${expectedRev}; re-read and re-apply`, { current: current.data });
      }
      const data = {
        ...current.data,
        ...unmanaged(change.patch),
        rev: rev + 1,
        updated_at: this.deps.clock.now().toISOString(),
        machine: await this.deps.machine.get(),
      };
      return this.write(path, { data, body: change.body ?? current.body });
    });
  }

  /**
   * Soft-deletes an entity (WL-08).
   * @param ref - Entity reference.
   * @param expectedRev - Current revision.
   * @param by - Who deletes.
   * @param reason - Why.
   * @returns The stored record.
   * @throws {WarlogError} `VALIDATION` when already deleted; `CONFLICT`; `NOT_FOUND`.
   */
  async softDelete(ref: EntityRef, expectedRev: number, by: string, reason: string): Promise<EntityRecord> {
    const current = await this.read(ref);
    if (current.data['deleted_at'] !== undefined) {
      throw new WarlogError('VALIDATION', `${ref.type} ${ref.id} is already deleted`, { id: ref.id });
    }
    const patch = { deleted_at: this.deps.clock.now().toISOString(), deleted_by: by, delete_reason: reason };
    return this.update(ref, { patch }, expectedRev);
  }

  /**
   * Restores a soft-deleted entity (WL-08).
   * @param ref - Entity reference.
   * @param expectedRev - Current revision.
   * @returns The stored record.
   * @throws {WarlogError} `VALIDATION` when not deleted; `CONFLICT`; `NOT_FOUND`.
   */
  async restore(ref: EntityRef, expectedRev: number): Promise<EntityRecord> {
    const current = await this.read(ref);
    if (current.data['deleted_at'] === undefined) {
      throw new WarlogError('VALIDATION', `${ref.type} ${ref.id} is not deleted`, { id: ref.id });
    }
    return this.update(ref, { patch: { deleted_at: undefined, deleted_by: undefined, delete_reason: undefined } }, expectedRev);
  }

  /**
   * Runs a critical section under the entity's lock.
   * @param path - Entity file path.
   * @param section - Work to do.
   * @returns The section's result.
   */
  private async locked<T>(path: string, section: () => Promise<T>): Promise<T> {
    const release = await this.deps.fs.lock(path);
    try {
      return await section();
    } finally {
      await release();
    }
  }

  /**
   * Writes a record atomically.
   * @param path - Entity file path.
   * @param record - Record to write.
   * @returns The record as written (undefined fields dropped).
   */
  private async write(path: string, record: EntityRecord): Promise<EntityRecord> {
    const text = stringifyFrontMatter(record);
    await this.deps.fs.writeFileAtomic(path, text);
    return parseFrontMatter(text, path);
  }
}
