/**
 * Writes tracker entities for one call: persists through the entity repository, applies the file
 * to the view (read-your-writes) and queues the activity records appended after success
 * (WL-04, WL-08, WL-42, plan §3.6).
 */
import type { WarlogError } from '../../core/errors/warlog-error.ts';
import type { OperationContext } from '../../core/mediator/operation-context.ts';
import type { IndexedEntity } from '../../core/ports/store-view.port.ts';
import type { ActivityAction, ActivityInput } from '../../core/storage/activity-log.ts';
import type { DeletionInfo, EntityChange } from '../../core/storage/entity-file-repository.ts';
import type { EntityRecord, EntityRef } from '../../core/storage/entity-ref.ts';
import type { EntityStore } from '../../core/storage/entity-store.ts';

/** One activity record about the written entity. */
export interface ActivityEvent {
  /** Action. */
  readonly action: ActivityAction;
  /** Short summary (titles only, no user content beyond them). */
  readonly summary: string;
  /** Whether the change used `force`. */
  readonly forced?: boolean;
  /** Changed field, previous and new values (updates). */
  readonly extra?: Readonly<Record<string, unknown>>;
  /** Entity the record is about when not the written file itself (e.g. a subtask inside its task). */
  readonly subject?: ActivitySubject;
}

/** Entity named by an activity record. */
export interface ActivitySubject {
  /** Entity type (`subtask`, …). */
  readonly type: string;
  /** Entity id. */
  readonly id: string;
}

/**
 * Reference of an indexed entity.
 * @param entity - Entity.
 * @returns Its reference.
 */
export function refOf(entity: IndexedEntity): EntityRef {
  const taskId = entity.record.data['task_id'];
  return {
    type: entity.type,
    id: entity.id,
    scope: entity.scope,
    ...(entity.projectId === undefined ? {} : { projectId: entity.projectId }),
    ...(entity.type === 'comment' && typeof taskId === 'string' ? { taskId } : {}),
  };
}

/**
 * Activity record fields of an event about an entity.
 * @param ref - Written entity.
 * @param repoKey - Repository key, for repository data.
 * @param event - Event.
 * @returns Record fields.
 */
function activityInput(ref: EntityRef, repoKey: string | undefined, event: ActivityEvent): ActivityInput {
  return {
    action: event.action,
    entity_type: event.subject?.type ?? ref.type,
    entity_id: event.subject?.id ?? ref.id,
    ...(ref.projectId === undefined ? {} : { project_id: ref.projectId }),
    ...(repoKey === undefined ? {} : { repo_key: repoKey }),
    summary: event.summary,
    ...(event.forced === true ? { forced: true } : {}),
    ...(event.extra === undefined ? {} : { extra: event.extra }),
  };
}

/** Writes entities and queues their activity. */
export class TrackerWriter {
  /** Store of the call. */
  private readonly store: EntityStore;
  /** Call context. */
  private readonly context: OperationContext;

  /**
   * Creates the writer.
   * @param store - Store of the call's roots.
   * @param context - Call context.
   */
  constructor(store: EntityStore, context: OperationContext) {
    this.store = store;
    this.context = context;
  }

  /**
   * Creates an entity and records `created`.
   * @param ref - Reference (id generated by the caller).
   * @param fields - Front-matter fields.
   * @param body - Markdown body.
   * @param summary - Activity summary.
   * @param more - Further records (e.g. an automatic block).
   * @returns The stored record.
   * @throws {WarlogError} `CONFLICT` when it exists; `VALIDATION`; `NO_REPO_CONTEXT`.
   */
  async create(ref: EntityRef, fields: Readonly<Record<string, unknown>>, body: string, summary: string, more: readonly ActivityEvent[] = []): Promise<EntityRecord> {
    const record = await this.store.repo.create(ref, fields, body);
    await this.applied(ref, [{ action: 'created', summary }, ...more]);
    return record;
  }

  /**
   * Updates an entity based on the revision seen in the view (WL-42) and records the events.
   * @param entity - Entity as seen.
   * @param change - Patch and optional body.
   * @param events - Activity records.
   * @returns The stored record.
   * @throws {WarlogError} `CONFLICT` (`stale_rev`) when the file changed since; `NOT_FOUND`.
   */
  async update(entity: IndexedEntity, change: EntityChange, events: readonly ActivityEvent[]): Promise<EntityRecord> {
    const ref = refOf(entity);
    const record = await this.store.repo.update(ref, change, Number(entity.record.data['rev']));
    await this.applied(ref, events);
    return record;
  }

  /**
   * Soft-deletes an entity (WL-08) and records `deleted`.
   * @param entity - Entity as seen.
   * @param deletion - Who and why.
   * @param summary - Activity summary.
   * @returns The stored record.
   * @throws {WarlogError} `VALIDATION` when already deleted; `CONFLICT`; `NOT_FOUND`.
   */
  async softDelete(entity: IndexedEntity, deletion: DeletionInfo, summary: string): Promise<EntityRecord> {
    const ref = refOf(entity);
    const record = await this.store.repo.softDelete(ref, Number(entity.record.data['rev']), deletion);
    await this.applied(ref, [{ action: 'deleted', summary }]);
    return record;
  }

  /**
   * Soft-deletes an entity this call has just created (`rev: 1`), e.g. an imported record that was
   * removed in its source.
   * @param ref - Entity reference.
   * @param deletion - Who and why.
   * @param summary - Activity summary.
   * @returns The stored record.
   * @throws {WarlogError} `CONFLICT` when it changed since its creation.
   */
  async softDeleteCreated(ref: EntityRef, deletion: DeletionInfo, summary: string): Promise<EntityRecord> {
    const record = await this.store.repo.softDelete(ref, 1, deletion);
    await this.applied(ref, [{ action: 'deleted', summary }]);
    return record;
  }

  /**
   * Restores a soft-deleted entity (WL-08) and records `restored`.
   * @param entity - Entity as seen.
   * @param summary - Activity summary.
   * @returns The stored record.
   * @throws {WarlogError} `VALIDATION` when not deleted; `CONFLICT`; `NOT_FOUND`.
   */
  async restore(entity: IndexedEntity, summary: string): Promise<EntityRecord> {
    const ref = refOf(entity);
    const record = await this.store.repo.restore(ref, Number(entity.record.data['rev']));
    await this.applied(ref, [{ action: 'restored', summary }]);
    return record;
  }

  /**
   * Refreshes the view with the written file and queues the activity records.
   * @param ref - Written entity.
   * @param events - Activity records.
   * @returns When done.
   */
  private async applied(ref: EntityRef, events: readonly ActivityEvent[]): Promise<void> {
    await this.context.index.refresh(await this.store.paths.pathFor(ref));
    const root = this.store.paths.rootOf(ref.scope);
    const repoKey = ref.scope === 'repo' ? this.context.roots.repository?.key : undefined;
    this.context.activity.push(...events.map((event) => ({ root, input: activityInput(ref, repoKey, event) })));
  }
}
